[package]
name = "front-end"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.10"
serde = { version = "1.0.137", features = ["derive"] }
yew = "0.19.3"
yew-hooks = "0.1.54"

[profile.release]
lto = true
